import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Provider } from "react-redux";
import { makeStore } from "./redux/UiStore";
import StoreProvider from './StoreProvider';
import Navbar from "@/components/base/Navbar";
import AuthProvider from "@/components/AuthProvider/AuthProvider"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Airbnb clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>

          <StoreProvider>
            {/* <Navbar /> */}
            {children}
          </StoreProvider>
        </AuthProvider>
      </body>
    </html >
  );
}
